### ISSUE TITLE
Desenvolver ou Escolher uma aplicação Web com suporte a WebRTC.

### ISSUE THREAD

**Issue by ArthurAnastopulos** [Sistema-Multimedia-2022-1/SMU2022-Nidhoogr-Yggdrasil#1]
Apresentação de jogo Web como possibilidade de aplicação feita com WebRTC: [catalogo-de-jogos](https://github.com/boidacarapreta/catalogo-de-jogos#no-ifsc-c%C3%A2mpus-s%C3%A3o-jos%C3%A9) de @boidacarapreta

**Comment by ArthurAnastopulos** [comment]
A aplicação Web escolhida para o uso durante a Disciplina de **SMU 2022.1** foi [**Nidhoogr-Yggdrasil**](https://github.com/boidacarapreta/arc20202-Nidhoogr-Yggdrasil) de @gabrielluizep e @leonardodod

**Comment by gabrielluizep** [comment]
Deixo minha recomendação de estudar bem o phaser antes de começar a desenvolver. Boa sorte!
