### ISSUE TITLE
Validar registro de cliente em servidor

### ISSUE THREAD

**Issue by ArthurAnastopulos** [Sistema-Multimedia-2022-1/SMU2022-Nidhoogr-Yggdrasil#7]
Apresentar em aula para o professor @boidacarapreta a aplicação em funcionamento.

**Comment by jeffersonbcr** [comment]
# Validar registro de cliente em servidor
## Validação de comunicação entre troca de mensagens entre servidor e cliente
A validação do comunicação entre o registro de clientes foi feita apenas por mensagens jogadas na parte do cliente parte web por console e por parte de console no terminal,sendo assim ambas mensagens deve ser as mesmas para ter a certeza que o processo está correto. A solução da validação do registro de cliente para servidor está sendo feita por meio de comunicação socket onde se troca informações do cliente para o servidor validar em uma porta, abaixo é possível identificar a mensagem na parte do cliente e abaixo dela a parte da confirmação na parte do servidor.
![Imagem na parte do cliente](https://user-images.githubusercontent.com/58866006/172279546-fd53fda3-c472-4925-af30-f71badb37d96.png) 
Informação do cliente
![image](https://user-images.githubusercontent.com/58866006/172279920-746d0adf-cf70-4da7-b26f-bc9e6bbef4e6.png)
Informação do servidor
## Validação de cliente adentrando uma sessão
Para a validação do primeiro cliente foi criado um array na parte do servidor que armazena os clientes de uma sessão,sendo assim caso o array seja vazio ele irá validar este cliente como sendo o dono da "sala" o mesmo receberá uma flag "isRoomOwner: true",os seguintes clientes que adentrarem a sessão serão validados de acordo de clientes na sala até cair no caso onde irá existir 4 clientes na sessão e impedirá novos clientes que adentre a sessão,como os novos clientes não são donos da sala irão receber flag "isRoomOwner: false".
![image](https://user-images.githubusercontent.com/58866006/172279546-fd53fda3-c472-4925-af30-f71badb37d96.png) 
Primeiro cliente criando a sessão.
![image](https://user-images.githubusercontent.com/58866006/172279920-746d0adf-cf70-4da7-b26f-bc9e6bbef4e6.png)
Confirmação de primeiro cliente criando sessão.

![image](https://user-images.githubusercontent.com/58866006/172280487-0af75706-66f6-446a-9210-626d9c81a807.png)
Segundo cliente adentrando a sessão
![image](https://user-images.githubusercontent.com/58866006/172280603-204297ed-d4f8-4d41-a805-2e02ace8d812.png)
Confirmação do servidor que segundo cliente adentrou a sessão e com informação de todos os clientes na sessão.

![image](https://user-images.githubusercontent.com/58866006/172281296-b4c4a973-c571-4cda-ad62-e56cf288c99a.png)
Terceiro cliente adentrando a sessão
![image](https://user-images.githubusercontent.com/58866006/172281366-e67ef818-6dc2-4843-9bf1-8260534f29cd.png)
Confirmação do servidor que terceiro cliente adentrou a sessão e com informação de todos os clientes na sessão.

![image](https://user-images.githubusercontent.com/58866006/172281427-f17c16c7-93b8-4573-a80e-810d786a7f0a.png)
Quarto cliente adentrando a sessão
![image](https://user-images.githubusercontent.com/58866006/172281504-04987081-dcbb-47fc-ad21-2a2e878a9109.png)
Confirmação do servidor que quarto cliente adentrou a sessão e com informação de todos os clientes na sessão.

![image](https://user-images.githubusercontent.com/58866006/172281583-ae1ff5e4-38fb-4f02-98a2-0ffd4b4b9c99.png)
Quinto cliente adentrando a sessão e sendo barrado por lotação de players e não teve dados criados.
![image](https://user-images.githubusercontent.com/58866006/172282157-faac2450-7341-4070-80c3-71447e0b6f4d.png)
Mensagem web que sala está cheia na parte web.
![image](https://user-images.githubusercontent.com/58866006/172282023-feb290ac-bb8e-4eaa-a82c-b6f87be24e68.png)
Confirmação do servidor que quinto cliente quer adentrar a sessão porém é barrado por validação de número de players.

## Validação de clientes para sair de uma sessão 
A validação de desconexão de um cliente é feita de duas maneiras caso ele aperta a tecla de sair da sessão ou caso ele decida dar um "refresh" na página será considera uma desconexão da sessão por identificação de "socket ID" o servidor é capaz de retirar da sessão e registrar que o cliente desconectou da sessão,para cada player que desconectar é enviado informação para todos os demais jogadores que se desconectou. A flag que identifica os usuários é atualizada por ordem de chegada dos clientes a sessão, sendo assim caso o dono da sala saia cabe ao sucessor dele em ordem receber a flag de "isRoomOwner: true" até que reste apenas um jogador.

![image](https://user-images.githubusercontent.com/58866006/172283413-31d2f3e2-4de7-4a18-9436-d9165b2bfa9d.png)
Exemplo de Clientes confirmados pelo servidor.
![image](https://user-images.githubusercontent.com/58866006/172283489-1f1b79e3-bf73-4aea-9971-52b90a6bdf7d.png)
caso de dono da sala ter desconectado por meio de "refresh" da página,sendo assim seu sucessor recebeu a flag de dono da sala.

![image](https://user-images.githubusercontent.com/58866006/172283800-8c30c52d-6ead-47c3-940e-950016c7ca27.png)
Cliente dois recebendo aviso que cliente um se desconectou da sessão.
![image](https://user-images.githubusercontent.com/58866006/172283824-8d98d3e7-8d52-4d4d-96b7-9de5862b30b1.png)
Cliente três recebendo aviso que cliente um se desconectou da sessão.
![image](https://user-images.githubusercontent.com/58866006/172283845-7041a157-a17f-4ee8-b77d-bf41d544bb83.png)
Cliente quatro recebendo aviso que cliente um se desconectou da sessão.

![image](https://user-images.githubusercontent.com/58866006/172284284-65cc0b16-339e-4999-aabd-7be5aef29d22.png)
Cliente se desconectando por meio de leitura de tecla "F".

## Passos para teste do código
Estas foram as validações realizados para registro de clientes em servidor, para executar o código é necessário seguir os seguintes passos:
- npm install
- npm run build
- npm run start
- Abrir o navegador e colar: http://localhost:1506/
